### ISSUE TITLE
add confirmation step in "done" button

### ISSUE THREAD

**Issue by alvseven** [LukeberryPi/phived#7]
Would be nice if "done" button has a confirmation step before remove the task, it could be a modal or just change the button text to "remove" or something like this

**Comment by LukeberryPi** [comment]
modals are a big no-no for this project, since the idea is to keep motion/distraction at a minimum.

about the text change onClick => task done onSecondClick, any suggestions to what that text could be? interested to hear your ideas.

q: is the intention of this to avoid losing a task on an accidental click? if so, i might have a feature in mind that solves this issue in a different manner.

**Comment by Allyhere** [comment]
> modals are a big no-no for this project, since the idea is to keep motion/distraction at a minimum.
> 
> about the text change onClick => task done onSecondClick, any suggestions to what that text could be? interested to hear your ideas.
> 
> q: is the intention of this to avoid losing a task on an accidental click? if so, i might have a feature in mind that solves this issue in a different manner.

Every action that cannot be undone needs a confirmation step to avoid frustrating accidents, it's a well know design pattern. If you could elaborate more about this feature, we could implement it

**Comment by LukeberryPi** [comment]
the intention is to briefly enable the possibility of "undoing" the "done" on a task in the future, as in to bring it back to the list. i will open an issue on this soon™, and we can develop this idea further over there.

closing this for now.
